/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a Supabase magic-link email
         * @description Server-side wrapper around `supabase.auth.signInWithOtp`. Sends a one-time link to the supplied email. Public — no auth required.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MagicLinkBody"];
                };
            };
            responses: {
                /** @description Magic-link email enqueued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MagicLinkResponse"];
                    };
                };
                /** @description Request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Supabase OTP rate limit hit (free tier: 4/hour/email). */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Upstream Supabase error. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Headless password sign-in + auto-minted PAT
         * @description Password sign-in for CLI / agent callers. Returns the Supabase session AND a freshly-minted Bearer PAT in a single response so the caller can immediately authenticate subsequent requests without a browser.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SigninBody"];
                };
            };
            responses: {
                /** @description Authenticated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SigninResponse"];
                    };
                };
                /** @description Invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Headless sign-up + auto-minted PAT
         * @description Provisions a user via the Supabase admin API with `email_confirm: true` so no email click is required, then signs them in and mints a PAT. Intended for QA / CLI environments — production sign-up should still use the magic-link path.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupBody"];
                };
            };
            responses: {
                /** @description User created + signed in. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignupResponse"];
                    };
                };
                /** @description Email already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns service identity, current environment, and a server timestamp. Always public.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Unhandled error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API version discovery
         * @description Discovery endpoint that points clients (CLI, agents, browsers) at the OpenAPI spec and the Scalar docs UI. Public.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API banner. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiVersionResponse"];
                    };
                };
                /** @description Unhandled error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's tokens
         * @description Returns every PAT the calling user owns, without the secret hash. RLS enforces ownership.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListTokensResponse"];
                    };
                };
                /** @description Not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Issue a personal access token
         * @description Issuance is session-authenticated — a logged-in user mints PATs via the web app. PATs cannot mint other PATs (chicken-and-egg). The raw secret is returned exactly once.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTokenBody"];
                };
            };
            responses: {
                /** @description Token created. Capture the `token` field — it is unrecoverable. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateTokenResponse"];
                    };
                };
                /** @description Not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal access token
         * @description Soft-delete: sets `revoked_at = now()` so the row stays in the audit trail. The bearer middleware rejects revoked rows.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Token id from `GET /api/v1/tokens`. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token revoked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Token not found or already revoked. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a workspace invite token
         * @description Caller must be signed in. Caller email must match invite email. Adds membership in the invite's workspace + role; stamps acceptance on the invite.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteAcceptBody"];
                };
            };
            responses: {
                /** @description Accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteAcceptResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Invite email does not match caller. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Token invalid. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Invite already accepted / revoked / expired. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/active-workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the active workspace for the current session
         * @description Validates membership, then sets the `bk_active_ws` httpOnly cookie. Supabase JWT is untouched.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActiveWorkspaceBody"];
                };
            };
            responses: {
                /** @description Cookie set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveWorkspaceResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Caller is not a member of the target workspace. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Introspect the authenticated principal
         * @description Returns the signed-in user, all workspaces they belong to, and the selected active workspace (driven by the bk_active_ws cookie).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Identity snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspaces the caller belongs to
         * @description RLS-filtered list of every workspace where the caller has an active membership.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceListResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create workspace + auto-enrol caller as owner
         * @description Wraps the `bunkai_bootstrap_workspace` SECURITY DEFINER RPC so the workspace row and the owner-membership row are inserted in a single transaction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceCreateBody"];
                };
            };
            responses: {
                /** @description Workspace created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceCreateResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Slug already in use. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Request body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single workspace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workspace. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Workspace not found or not visible. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update workspace metadata
         * @description Owner-only. Today only `name` is mutable; slug rotation is post-MVP.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspacePatchBody"];
                };
            };
            responses: {
                /** @description Updated workspace. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Caller is not an owner. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/workspaces/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspace invites
         * @description RLS limits results to admins/owners of the workspace.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invite list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceInviteListResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Issue a workspace invite
         * @description Admin/owner only. Generates a one-time token; returns the raw token + accept_url in the body. MVP does not send an email — share the URL out-of-band.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceInviteCreateBody"];
                };
            };
            responses: {
                /** @description Invite created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceInviteCreateResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Caller is not an admin/owner. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Validation failed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate (resend) a workspace invite token
         * @description Generates a new secret + extends expiry by 7 days. Clears any prior acceptance/revocation. Admin/owner only via RLS.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    inviteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotated invite. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceInviteResendResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Invite not found or no permission. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /** Revoke a workspace invite */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    inviteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceInviteDeleteResponse"];
                    };
                };
                /** @description Caller is not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Invite not found or no permission. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Canonical error envelope returned by every `/api/v1` route on failure. */
        ErrorEnvelope: {
            error: {
                /**
                 * @description Machine-readable error code. Branch on this value, not on `message`.
                 * @enum {string}
                 */
                code: "bad_request" | "validation_failed" | "unauthorized" | "forbidden" | "not_found" | "method_not_allowed" | "conflict" | "idempotency_key_required" | "idempotency_key_invalid" | "rate_limited" | "internal_error" | "upstream_error";
                /** @description Human-readable error description. */
                message: string;
                /** @description Optional structured details. For validation errors this is the ZodError issues array. */
                details?: unknown;
                /** @description Echoed `x-request-id`. Quote this in bug reports. */
                request_id?: string;
            };
        };
        MagicLinkResponse: {
            /** @enum {boolean} */
            ok: true;
        };
        MagicLinkBody: {
            /**
             * Format: email
             * @example tester@bunkai.io
             */
            email: string;
            /**
             * @description Root-relative path to land on after the OTP exchange. Defaults to `/projects`.
             * @example /projects
             */
            next?: string;
        };
        SigninResponse: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string | null;
            };
            session: {
                access_token: string;
                refresh_token: string;
                expires_at?: number;
                token_type?: string;
            };
            pat: {
                token: string;
                /** Format: uuid */
                id: string;
                name: string | null;
                scopes: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
                /** Format: date-time */
                expires_at: string | null;
            };
            warning: string;
        };
        SigninBody: {
            /**
             * Format: email
             * @example qa.user@example.com
             */
            email: string;
            password: string;
            pat_name?: string;
            pat_scopes?: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
            pat_expires_in_days?: number;
        };
        SignupResponse: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string | null;
            };
            session: {
                access_token: string;
                refresh_token: string;
                expires_at?: number;
                token_type?: string;
            };
            pat: {
                token: string;
                /** Format: uuid */
                id: string;
                name: string | null;
                scopes: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
                /** Format: date-time */
                expires_at: string | null;
            };
            warning: string;
        };
        SignupBody: {
            /**
             * Format: email
             * @example qa.user@example.com
             */
            email: string;
            password: string;
            pat_name?: string;
            pat_scopes?: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
            pat_expires_in_days?: number;
        };
        HealthResponse: {
            /** @enum {boolean} */
            ok: true;
            /** @example bunkai-tms */
            service: string;
            /** @enum {string} */
            env: "local" | "staging" | "production";
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the probe.
             */
            ts: string;
        };
        ApiVersionResponse: {
            /** @enum {string} */
            version: "v1";
            /** @example /api/openapi */
            openapi: string;
            /** @example /api/docs */
            docs: string;
            /** @enum {string} */
            status: "live";
        };
        CreateTokenResponse: {
            /** Format: uuid */
            id: string;
            /**
             * @description Raw PAT in the form `bk_pat_<prefix>.<secret>`. Shown ONCE in this response. The server only stores SHA-256(secret).
             * @example bk_pat_AbCdEfGhIjKl.MnOpQrStUv...
             */
            token: string;
            name: string | null;
            scopes: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
            /** Format: uuid */
            workspace_id: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** @example Store this token now — it cannot be retrieved later. */
            warning: string;
        };
        CreateTokenBody: {
            /**
             * @description Human-readable label shown in the token-management UI.
             * @example ci-pipeline
             */
            name?: string;
            /** @description Scopes granted to this token. At least one required. */
            scopes: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
            /**
             * Format: uuid
             * @description Restrict the token to a single workspace. Omit for cross-workspace tokens.
             */
            workspace_id?: string;
            /** @description TTL in days. Omit for non-expiring tokens. Max 365. */
            expires_in_days?: number;
        };
        ListTokensResponse: {
            tokens: components["schemas"]["TokenSummary"][];
        };
        TokenSummary: {
            /** Format: uuid */
            id: string;
            name: string | null;
            scopes: ("atc:read" | "atc:write" | "run:execute" | "workspace:admin")[];
            /** Format: uuid */
            workspace_id: string | null;
            /** @description First 12 chars of the secret. Safe to display. */
            token_prefix: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            revoked_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InviteAcceptResponse: {
            /** @enum {boolean} */
            ok: true;
            /** Format: uuid */
            workspace_id: string;
            /** @enum {string} */
            role: "viewer" | "member" | "admin";
        };
        InviteAcceptBody: {
            token: string;
        };
        ActiveWorkspaceResponse: {
            /** @enum {boolean} */
            ok: true;
            /** Format: uuid */
            active_workspace_id: string;
        };
        ActiveWorkspaceBody: {
            /** Format: uuid */
            workspace_id: string;
        };
        MeResponse: {
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string | null;
            };
            workspaces: {
                /** Format: uuid */
                id: string;
                slug: string;
                name: string;
                /** @enum {string} */
                plan: "community" | "cloud" | "enterprise";
                /** Format: uuid */
                owner_user_id: string;
                /** Format: date-time */
                created_at: string;
            }[];
            /** Format: uuid */
            active_workspace_id: string | null;
            auth: {
                /** @enum {string} */
                source: "cookie" | "bearer";
                scopes: string[];
            };
        };
        WorkspaceCreateResponse: {
            workspace: components["schemas"]["Workspace"];
        };
        Workspace: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** Format: uuid */
            owner_user_id: string;
            /** @enum {string} */
            plan: "community" | "cloud" | "enterprise";
            /** Format: date-time */
            created_at: string;
        };
        WorkspaceCreateBody: {
            /** @example Acme QA */
            name: string;
            /** @example acme-qa */
            slug: string;
        };
        WorkspaceListResponse: {
            workspaces: components["schemas"]["Workspace"][];
        };
        WorkspaceResponse: {
            workspace: components["schemas"]["Workspace"];
        };
        WorkspacePatchBody: {
            name?: string;
        };
        WorkspaceInviteCreateResponse: {
            invite: components["schemas"]["WorkspaceInvite"];
            /** @description Raw token. Returned exactly once. */
            token: string;
            /** Format: uri */
            accept_url: string;
            warning: string;
        };
        WorkspaceInvite: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "viewer" | "member" | "admin";
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** @enum {string} */
            status?: "pending" | "accepted" | "revoked" | "expired";
        };
        WorkspaceInviteCreateBody: {
            /** Format: email */
            email: string;
            /**
             * @default member
             * @enum {string}
             */
            role: "viewer" | "member" | "admin";
        };
        WorkspaceInviteListResponse: {
            invites: components["schemas"]["WorkspaceInvite"][];
        };
        WorkspaceInviteResendResponse: {
            invite: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                /** @enum {string} */
                role: "viewer" | "member" | "admin";
                /** Format: date-time */
                expires_at: string;
                /** Format: date-time */
                created_at: string;
            };
            token: string;
            /** Format: uri */
            accept_url: string;
            warning: string;
        };
        WorkspaceInviteDeleteResponse: {
            /** @enum {boolean} */
            ok: true;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
